import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PrintDataProvider } from "./printDataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "タイヤ見積もりアプリ",
  description: "Generated by create next app",
  robots: { // ウェブ検索で表示されないように設定
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <PrintDataProvider>
        <body className={inter.className}>{children}</body>
      </PrintDataProvider>
    </html>
  );
}
